//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ID { get; set; }
        public Nullable<int> HouseID { get; set; }
        public string Number { get; set; }
        public Nullable<float> Area { get; set; }
        public Nullable<int> CountOfRooms { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<long> BuildingCost { get; set; }
        public Nullable<int> ApartmentValueAdded { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual House House { get; set; }
    }
}
