//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDomNSLEEntities : DbContext
    {
        public BaseDomNSLEEntities()
            : base("name=BaseDomNSLEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartaments> Apartaments { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<ResidentialComplex> ResidentialComplex { get; set; }
        public virtual DbSet<Coefficients> Coefficients { get; set; }
    }
}
