//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coefficients
    {
        public double area { get; set; }
        public double areac { get; set; }
        public int rooms { get; set; }
        public double roomsc { get; set; }
        public double apartmentc { get; set; }
        public double housec { get; set; }
        public double complexc { get; set; }
        public double basec { get; set; }
    }
}
